name: Tests

on:
  push:
    paths:
    - '**.zig'
  pull_request:
    paths:
    - '**.zig'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - uses: goto-bus-stop/setup-zig@v1
      with:
        version: master

    - name: Checkout ZKG
      uses: actions/checkout@v2
      with:
        repository: 'mattnite/zkg'
        path: .tools/zkg.d

    - name: Setup ZKG
      working-directory: .tools/zkg.d
      shell: pwsh
      run: |
        zig build

        Copy-Item ./zig-cache/bin/zkg* ..

    - name: Build
      run: |
        ./.tools/zkg fetch
        zig build test